title: wangtt's Homepage
page-top-title: wangtt
top-section-bg-text: Software Engineering
home-subtitle: TongTong Wang&ensp;|&ensp;王彤彤
copyright-text: '&copy; TongTong Wang 2023-2024. All Rights Reserved.'
